#
#  Licensed to the Apache Software Foundation (ASF) under one or more
#  contributor license agreements.  See the NOTICE file distributed with
#  this work for additional information regarding copyright ownership.
#  The ASF licenses this file to You under the Apache License, Version 2.0
#  (the "License"); you may not use this file except in compliance with
#  the License.  You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
#
version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
    # Stick to Cassandra 3.x
    - dependency-name: "org.apache.cassandra:*"
      update-types: ["version-update:semver-major"]
    - dependency-name: "com.datastax.cassandra:*"
      update-types: ["version-update:semver-major"]
    # Newer versions require Java 9
    - dependency-name: "com.conversantmedia:disruptor"
    # Stick to Jakarta EE 9.x
    - dependency-name: "jakarta.platform:jakarta.jakartaee-bom"
    # Jetty 9.x is the last with an internal logging API
    - dependency-name: "org.eclipse.jetty:jetty-bom"
      update-types: ["version-update:semver-major"]
    # Stick to Java EE 8
    - dependency-name: "javax.activation:javax.activation-api"
      update-types: ["version-update:semver-major"]
    - dependency-name: "javax.inject:javax.inject"
      update-types: ["version-update:semver-major"]
    - dependency-name: "javax.jms:javax.jms-api"
      update-types: ["version-update:semver-major"]
    - dependency-name: "javax.mail:javax.mail-api"
      update-types: ["version-update:semver-major"]
    - dependency-name: "javax.persistence:javax.persistence-api"
      update-types: ["version-update:semver-major"]
    - dependency-name: "javax.servlet.jsp:javax.servlet.jsp-api"
      update-types: ["version-update:semver-major"]
    - dependency-name: "javax.servlet:javax.servlet-api"
      update-types: ["version-update:semver-major"]
    # Stick to OSGI 6.0
    - dependency-name: "org.osgi:org.osgi.core"
      update-types: ["version-update:semver-major"]
    # Stick to MongoDB 3.x/4.x according to the module
    - dependency-name: "org.mongodb:*"
      update-types: ["version-update:semver-major"]
    # Spring Boot 3.x has the Spring lookup already integrated
    - dependency-name: "org.springframework:spring-framework-bom"
      update-types: ["version-update:semver-major"]
    - dependency-name: "org.springframework.boot:*"
      update-types: ["version-update:semver-major"]
    # No automatic upgrades at all for `slf4j-api` 1.7.25
    - dependency-name: "org.slf4j:*"
    # Only patch-level upgrades for Logback
    - dependency-name: "ch.qos.logback:*"
      update-types: ["version-update:semver-major", "version-update:semver-minor"]
    # Keep EclipseLink at version 2.X (Java EE 8)
    - dependency-name: "org.eclipse.persistence:*"
      update-types: ["version-update:semver-major"]

- package-ecosystem: github-actions
  directory: /
  schedule:
    interval: daily
  open-pull-requests-limit: 10
