#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to you under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

name: auto-merge-dependabot

on:
  push:
    branches:
      - 'dependabot/**'

permissions:
  # The default GITHUB_TOKEN will be used to enable the "auto-merge" on the PR
  pull-requests: write

jobs:

  process-dependabot:
    # Skip this workflow on commits not pushed by Dependabot
    if: ${{ github.actor == 'dependabot[bot]' }}
    uses: apache/logging-parents/.github/workflows/process-dependabot-reusable.yaml@feat/dependabot-add-changelog
    permissions:
      contents: write
    secrets:
      AUTO_MERGE_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      CONTENT_WRITE_TOKEN: ${{ secrets.DEPENDABOT_TOKEN }}
      GPG_SECRET_KEY: ${{ secrets.GPG_SECRET_KEY }}
